import { useConnectModal } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useWalletClient } from 'wagmi';
import { useEffect } from 'react';
import Signer from '../components/Signer';

const Home: NextPage = () => {
  const { data: walletClient } = useWalletClient();
  const { openConnectModal } = useConnectModal();
  useEffect(() => {
    if (walletClient) {
      console.log('walletClient', walletClient);
    } else if (openConnectModal) {
      openConnectModal();
    }
  }, [walletClient])

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Signer walletClient={walletClient} />
    </div>
  );
};

export default Home;
